import 'dart:math';
import 'package:flutter/foundation.dart';
import '../models/models.dart';
import 'services_base.dart';

class ReferenceCodeService extends ServicesBase {
  /// Generate a unique 8-character reference code
  Future<String> generateCode(String adminId) async {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    final rnd = Random();

    while (true) {
      final code = String.fromCharCodes(
        Iterable.generate(
          8,
          (_) => chars.codeUnitAt(rnd.nextInt(chars.length)),
        ),
      );

      // Check if code already exists
      final snapshot = await referenceCodesDb.doc(code).get();
      if (!snapshot.exists) {
        final referenceCode = ReferenceCodeModel(
          code: code,
          adminId: adminId,
          createdAt: DateTime.now(),
        );
        await referenceCodesDb.doc(code).set(referenceCode.toJson());
        return code;
      }
    }
  }

  /// Create a custom reference code
  Future<bool> createCustomCode(String code, String adminId) async {
    try {
      final processedCode = code.trim().toUpperCase();
      if (processedCode.isEmpty) return false;

      // Check if code already exists
      final snapshot = await referenceCodesDb.doc(processedCode).get();
      if (snapshot.exists) {
        return false; // Code already taken
      }

      final referenceCode = ReferenceCodeModel(
        code: processedCode,
        adminId: adminId,
        createdAt: DateTime.now(),
      );
      await referenceCodesDb.doc(processedCode).set(referenceCode.toJson());
      return true;
    } catch (e) {
      if (kDebugMode) {
        print('Error creating custom code: $e');
      }
      return false;
    }
  }

  /// Validate a reference code and return the adminId if valid
  Future<String?> validateCode(String code) async {
    try {
      final processedCode = code.trim().toUpperCase();
      final snapshot = await referenceCodesDb.doc(processedCode).get();
      if (snapshot.exists) {
        final data = snapshot.data();
        if (data != null) {
          return data['adminId']?.toString();
        }
      }
      return null;
    } catch (e) {
      if (kDebugMode) {
        print('Error validating reference code: $e');
      }
      return null;
    }
  }

  /// Get all reference codes generated by an admin
  Future<List<ReferenceCodeModel>> getAdminCodes(String adminId) async {
    try {
      final snapshot = await referenceCodesDb
          .where('adminId', isEqualTo: adminId)
          .get();
      return snapshot.docs
          .map((e) => ReferenceCodeModel.fromJson(e.data()))
          .toList();
    } catch (e) {
      if (kDebugMode) {
        print('Error getting admin reference codes: $e');
      }
      return [];
    }
  }

  /// Get all users who joined using any of the codes from this admin
  Future<List<UserModel>> getReferredUsers(String adminId) async {
    try {
      final snapshot = await userDb
          .where('joinedByAdminId', isEqualTo: adminId)
          .get();
      return snapshot.docs.map((e) => UserModel.fromJson(e.data())).toList();
    } catch (e) {
      if (kDebugMode) {
        print('Error getting referred users: $e');
      }
      return [];
    }
  }

  /// Delete a reference code
  Future<bool> deleteCode(String code) async {
    try {
      await referenceCodesDb.doc(code).delete();
      return true;
    } catch (e) {
      if (kDebugMode) {
        print('Error deleting reference code: $e');
      }
      return false;
    }
  }
}
